// [{
//     "animal": "elephant",
//     "time": ["11:00","17:30"],
//     "notification_title":"Kąpiel Słoni",
//     "week_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
//     "month":[],
// },
// {
//     "animal": "turtle",
//     "time": ["11:30"],
//     "notification_title":"Żółwie Brunatne",
//     "week_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
//     "month":[],
// },
// {
//     "animal": "water_tunnel",
//     "time": ["12:00"],
//     "notification_title":"Nurkowania",
//     "week_days": ["Wednesday",],
//     "month":[],
// },
// {
//     "animal": "night_animals",
//     "time": ["13:00"],
//     "notification_title":"____",
//     "week_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
//     "month":["May", "June", "July", "August", "September"],
// },
// {
//     "animal": "lynx",
//     "time": ["14:00"],
//     "notification_title":"____",
//     "week_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
//     "month":[],
// },
// {
//     "animal": "hippo_house",
//     "time": ["15:00"],
//     "notification_title":"____",
//     "week_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
//     "month":[],
// },
// {
//     "animal": "ungulates",
//     "time": ["16:00"],
//     "notification_title":"____",
//     "week_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
//     "month":[],
// },
// {
//     "animal": "shark",
//     "time": ["17:00"],
//     "notification_title":"____",
//     "week_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
//     "month":[],
// },
// {
//     "animal": "sun_bear",
//     "time": ["18:00"],
//     "notification_title":"____",
//     "week_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
//     "month":[],
// },
// {
//     "animal": "south_america_house",
//     "time": ["19:00"],
//     "notification_title":"____",
//     "week_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
//     "month":[],
// },
// {
//     "animal": "penguin",
//     "time": ["20:00"],
//     "notification_title":"____",
//     "week_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
//     "month":[],
// },
// {
//     "animal": "monkey",
//     "time": ["21:00"],
//     "notification_title":"____",
//     "week_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
//     "month":[],
// },
// {
//     "animal": "reptiles",
//     "time": ["22:00"],
//     "notification_title":"____",
//     "week_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
//     "month":[],
// },
// {
//     "animal": "birds",
//     "time": ["23:00"],
//     "notification_title":"____",
//     "week_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
//     "month":[],
// },
// {
//     "animal": "amphibians",
//     "time": ["24:00"],  
//     "notification_title":"____",
//     "week_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
//     "month":[],
// },
// {
//     "animal": "insects",
//     "time": ["25:00"],
//     "notification_title":"____",
//     "week_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
//     "month":[],
// },
// {
//     "animal": "aquarium",
//     "time": ["26:00"],
//     "notification_title":"____",
//     "week_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
//     "month":[],
// },
// {
//     "animal": "farm_animals",
//     "time": ["27:00"],
//     "notification_title":"____",
//     "week_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
//     "month":[],
// },
// {
//     "animal": "arctic_animals",
//     "time": ["28:00"],
//     "notification_title":"____",
//     "week_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
//     "month":[],
// },
// {
//     "animal": "desert_animals",
//     "time": ["29:00"],  
//     "notification_title":"____",
//     "week_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
//     "month":[],
// },
// {
//     "animal": "jungle_animals",
//     "time": ["30:00"],
//     "notification_title":"____",
//     "week_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
//     "month":[],
// },
// {
//     "animal": "savannah_animals",
//     "time": ["31:00"],
//     "notification_title":"____",
//     "week_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
//     "month":[],
// }]